name: Build and Upload Converter

on:
  schedule:
    - cron: '0 0 * * 1' # Raz w tygodniu, w poniedziałki o północy
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        shell: pwsh
        run: .\installResources.ps1

      - name: Build executable with PyInstaller
        shell: pwsh
        run: pyinstaller --onefile converter.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: converter-exe
          path: dist/converter.exe
